[package]
name = "ive_launcher_win"
build = "build.rs"

[[bin]]
name = "IVE"

[dependencies]
winapi = {version = "0.3.9", features = ["winbase"]}

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
